<a href="https://colab.research.google.com/github/YassineKariim/AziureDmoDsbd/blob/master/tensorFlow%20Practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('yasine')

yasine


In [2]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [5]:
#create our first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#CHECK THE NUMBER OF DIMENSIONS OF A TENSOR
scalar.ndim

0

In [7]:
#create a verctor
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:

#create a matrix
matrix=tf.constant([[7,10],
                   [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
another_matrix=tf.constant([[7,10],
                   [10,7],
                    [10.0,88.1]],dtype=tf.float16)#sepicifiyin the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7. , 10. ],
       [10. ,  7. ],
       [10. , 88.1]], dtype=float16)>

In [14]:
#let's create a tensor
tensor =tf.constant([[[10,5,0],
                    [12,9,10]],
                    [[2,6,7],
                     [2,56,7]],
                     [[2,7,0],
                     [67,0,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  5,  0],
        [12,  9, 10]],

       [[ 2,  6,  7],
        [ 2, 56,  7]],

       [[ 2,  7,  0],
        [67,  0,  8]]], dtype=int32)>