<a href="https://colab.research.google.com/github/YassineKariim/AziureDmoDsbd/blob/master/TensorFlow_first_path.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('yasine')

yasine


In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
#create our first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#CHECK THE NUMBER OF DIMENSIONS OF A TENSOR
scalar.ndim

0

In [ ]:
#create a verctor
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:

#create a matrix
matrix=tf.constant([[7,10],
                   [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[7,10],
                   [10,7],
                    [10.0,88.1]],dtype=tf.float16)#sepicifiyin the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7. , 10. ],
       [10. ,  7. ],
       [10. , 88.1]], dtype=float16)>

In [ ]:
#let's create a tensor
tensor =tf.constant([[[10,5,0],
                    [12,9,10]],
                    [[2,6,7],
                     [2,56,7]],
                     [[2,7,0],
                     [67,0,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  5,  0],
        [12,  9, 10]],

       [[ 2,  6,  7],
        [ 2, 56,  7]],

       [[ 2,  7,  0],
        [67,  0,  8]]], dtype=int32)>

In [ ]:
#creating a tensor with tf.Variable()
changeable_tensor=tf.Variable([10,9])
uncheagebale_tensor=tf.constant([10,9])
changeable_tensor,uncheagebale_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  9], dtype=int32)>)

In [ ]:
import tensorflow as tf
not_shuffled= tf.constant([[12,76],
                         [12,101],
                         [9,9]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12,  76],
       [ 12, 101],
       [  9,   9]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12,  76],
       [  9,   9],
       [ 12, 101]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  9,   9],
       [ 12,  76],
       [ 12, 101]], dtype=int32)>

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#you can turn numpy arrays to tensors
import numpy as np
numpy_A=np.arange(1,25 ,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

In [ ]:
#create a tensor with a default data type
B=tf.constant([12.4,7])
B.dtype

tf.float32

In [ ]:
D=tf.cast(B,dtype=(tf.float16))
D.dtype

tf.float16

In [ ]:
import tensorflow as tf

# Assuming you have a tensor `data` with shape (4, 3)
data = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

# Sum all elements in the tensor
sum_result = tf.reduce_sum(data)

# Compute the mean along axis 0 (reduce the tensor along the first dimension)
mean_result = tf.reduce_mean(data, axis=0)

print("Sum result:", sum_result.numpy())
print("Mean result:", mean_result.numpy())


Sum result: 78
Mean result: [5 6 7]


In [ ]:
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([64, 53, 80, 44, 50, 28, 20, 31, 67, 21, 89, 36,  9, 58, 91, 76, 48,
       44, 11, 68, 70, 92, 55, 62, 23,  4, 92, 41, 57, 40, 37, 39, 10, 52,
       53, 89, 32, 69,  0,  2, 37, 68, 38,  5, 90, 95, 79, 20, 59, 68])>

In [ ]:
#find the minimum
C=tf.reduce_min(E)
C.numpy()

0

In [ ]:
#find the maximum
T=tf.reduce_max(E)
T.numpy()

95

In [ ]:
#find the mean
Z=tf.reduce_mean(E)
Z.numpy()

49

In [ ]:
#find the sum
Y=tf.reduce_sum(E)
Y.numpy()

2466

In [ ]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#find the positionnal mawimum
R=tf.argmax(F)
R

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=float32, numpy=25.690401>

In [ ]:
F.shape

TensorShape([50])

In [ ]:
F_squeezed=tf.squeeze(F)
F_squeezed,F_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [ ]:
#create some list
some_list=[0,1,2,3,4]
tf.one_hot(some_list,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>