<a href="https://colab.research.google.com/github/YassineKariim/AziureDmoDsbd/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('yasine')

yasine


In [2]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [5]:
#create our first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#CHECK THE NUMBER OF DIMENSIONS OF A TENSOR
scalar.ndim

0

In [7]:
#create a verctor
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:

#create a matrix
matrix=tf.constant([[7,10],
                   [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
another_matrix=tf.constant([[7,10],
                   [10,7],
                    [10.0,88.1]],dtype=tf.float16)#sepicifiyin the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7. , 10. ],
       [10. ,  7. ],
       [10. , 88.1]], dtype=float16)>

In [14]:
#let's create a tensor
tensor =tf.constant([[[10,5,0],
                    [12,9,10]],
                    [[2,6,7],
                     [2,56,7]],
                     [[2,7,0],
                     [67,0,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  5,  0],
        [12,  9, 10]],

       [[ 2,  6,  7],
        [ 2, 56,  7]],

       [[ 2,  7,  0],
        [67,  0,  8]]], dtype=int32)>

In [17]:
#creating a tensor with tf.Variable()
changeable_tensor=tf.Variable([10,9])
uncheagebale_tensor=tf.constant([10,9])
changeable_tensor,uncheagebale_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  9], dtype=int32)>)

In [5]:
import tensorflow as tf
not_shuffled= tf.constant([[12,76],
                         [12,101],
                         [9,9]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12,  76],
       [ 12, 101],
       [  9,   9]], dtype=int32)>

In [14]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12,  76],
       [  9,   9],
       [ 12, 101]], dtype=int32)>

In [6]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  9,   9],
       [ 12,  76],
       [ 12, 101]], dtype=int32)>

In [15]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [17]:
#you can turn numpy arrays to tensors
import numpy as np
numpy_A=np.arange(1,25 ,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [21]:
A.ndim

3